/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2015-04-14 06:20:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import transactionBean.ReportBean;
import java.util.ArrayList;
import java.sql.*;
import java.io.*;
import javax.servlet.*;
import transactionBean.*;
import utility.*;
import java.text.*;

public final class evaluatePerformance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<title>Evaluate Performance</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function IndvEvalFn(rollNbr){\r\n");
      out.write("\talert(\"Before redirecting\"+rollNbr);\r\n");
      out.write("\twindow.location = \"EvaluateSummaryRH?rollNbr=\"+rollNbr;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
  
	String Name = ""; 
	String displayMsg = " ";
	if(session.getAttribute(Constants.corpusBean) != null){
		CorpusBean myCorpus = new CorpusBean();
		myCorpus =  (CorpusBean) session.getAttribute(Constants.corpusBean);
		if(myCorpus.isAdmin()){
			Name = myCorpus.getFirstName().concat(" ").concat(myCorpus.getLastName());
		}else{
			//redirect block here
			response.sendRedirect("/Forex/LogOutRH");
		}
		if( request.getAttribute("Constants.DISPLAY_MSG") != null)
			 displayMsg= (String) request.getAttribute("Constants.DISPLAY_MSG");
	}else{
		//redirect block here
		response.sendRedirect("/Forex/LogOutRH");
	}
		
DecimalFormat df = new DecimalFormat("#,###");
	int rows= 1;
	String Forward = "Forward ";
	String tnx_type ="";
	ArrayList<EvaluateBean> report = new ArrayList<EvaluateBean>();
	if((session.getAttribute(Constants.EVALUATE_BEAN_LIST)) != null){
		report = (ArrayList<EvaluateBean>) session.getAttribute(Constants.EVALUATE_BEAN_LIST);
	}
	

      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<table border=\"0\" cellspacing=\"0\" width=\"95%\" align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"left\"><a href=\"/Forex/EvaluatePerformance\">Refresh</a></td>\r\n");
      out.write("\t\t\t<td align=\"right\"><a href=\"adminHome.jsp\">Home</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<table cellspacing=\"3\" cellpadding=\"3\" width=\"95%\" align=\"center\" border=\"2\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"7\" align=\"center\"><h1>PERFORMANCE EVALUATION</h1></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<h2>\r\n");
      out.write("\t\t\t\t<td align=\"center\">RANK</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">USER</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">CORPUS VALUE</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">SPOT BUYS</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">SPOT SELLS</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">FORWARD BUYS</td>\r\n");
      out.write("\t\t\t\t<td align=\"center\">FORWARD SELLS</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
 for (EvaluateBean iReport : report) { 
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print( iReport.getRank() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\"><a id=\"indvEvaluation\"\r\n");
      out.write("\t\t\t\thref=\"EvaluateSummaryRH?rollNbr=");
      out.print( iReport.getRollNbr() );
      out.write('"');
      out.write('>');
      out.print( iReport.getRollNbr() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print( df.format(iReport.getTotalValue()) );
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print( df.format(iReport.getNbrSales()) );
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print( df.format(iReport.getNbrPurchases()) );
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print( df.format(iReport.getNbrFwdSales()) );
      out.write("</td>\r\n");
      out.write("\t\t\t<td align=\"center\">");
      out.print( df.format(iReport.getNbrFwdPurchases()) );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
