/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2015-03-06 04:30:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<title>Forex Simulator</title>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\t$(\"loginform\")\r\n");
      out.write("\t\t\t.submit(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tif ($('#loading_image').length == 0) { //is the image on the form yet?\r\n");
      out.write("\t\t\t\t\t\t\t// add it just before the submit button\r\n");
      out.write("\t\t\t\t\t\t\t$(':submit')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.before(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'<img src=\"/images/load_one.gif\" style=\"display: none;\" alt=\"loading\" id=\"loading_image\">')\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$('#loading_image').show(); // show the animated image    \r\n");
      out.write("\t\t\t\t\t\t$(':submit', this).attr('disabled', 'disabled'); // disable double submits\r\n");
      out.write("\t\t\t\t\t\treturn true; // allow regular form submission\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction dil(form) {\r\n");
      out.write("\t\tfor (var i = 0; i < form.elements.length; i++) {\r\n");
      out.write("\t\t\tif (form.elements[i].value == \"\") {\r\n");
      out.write("\t\t\t\talert(\"Please Enter All Details\");\r\n");
      out.write("\t\t\t\tdocument.loginForm.rollNbr.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"templatemo_header_wrapper\">\r\n");
      out.write("\t\t<div id=\"templatemo_header\"></div>\r\n");
      out.write("\t\t<!-- end of templatemo_header -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"site_title\">Forex Simulator</div>\r\n");
      out.write("\t<!-- end of templatemo_menu_wrapper -->\r\n");
      out.write("\t<div align=\"center\" id=\"templatemo_content\">\r\n");
      out.write("\t\t<div class=\"content_box\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form name=loginForm onSubmit=\"return dil(this)\"\r\n");
      out.write("\t\t\t\taction=\"TransactionRH\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>USER NAME:</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"rollNbr\" maxlength=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"rollNbr\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>PASSWORD:</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" value=\"Submit\" /> <INPUT TYPE=RESET\r\n");
      out.write("\t\t\t\t\t\t\tVALUE=\"CLEAR\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end of content -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end of content -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
